<?php

declare(strict_types=1);

/*
 * APIMATICCalculatorZipLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCalculatorZipLib\Controllers;

use APIMATICCalculatorZipLib\Exceptions\ApiException;
use APIMATICCalculatorZipLib\Models\OperationTypeEnum;
use Core\Request\Parameters\QueryParam;
use Core\Request\Parameters\TemplateParam;
use CoreInterfaces\Core\Request\RequestMethod;

class SimpleCalculatorController extends BaseController
{
    /**
     * Calculates the expression using the specified operation.
     *
     * @param string $operation The operator to apply on the variables
     * @param float $x The LHS value
     * @param float $y The RHS value
     *
     * @return float Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function calculate(string $operation, float $x, float $y): float
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/{operation}')
            ->parameters(
                TemplateParam::init('operation', $operation)->serializeBy([OperationTypeEnum::class, 'checkValue']),
                QueryParam::init('x', $x),
                QueryParam::init('y', $y)
            );

        return $this->execute($_reqBuilder);
    }
}
